AdvancedBlog/urls.py
from django.conf.urls import  *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include("post.urls", namespace="post")),
    url(r'^comment/', include("comment.urls")),
    url(r'^', include("home.urls", namespace="home")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import  *
from django.contrib import admin

import post
from home import views

urlpatterns = [
    url(r'^$', views.IndexView, name="index"),
    url(r'^about$', views.AboutView, name="about"),
    url(r'^contact', views.ContactView, name="contact"),

]

post/urls.py
from django.conf.urls import url

from post import views

app_name = "post"

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)$', views.PostDetailView, name="detail"),
    url(r'^like/(?P<slug>[\w-]+)$', views.LikePostView, name="like"),
    url(r'^dislike/(?P<slug>[\w-]+)$', views.DislikeView, name="dislike"),
    url(r'^post/$', views.allpost, name="allpost"),
    url(r'^$', views.deneme, name="lcount"),

]

home/models.py
from django.db import models

# Create your models here.


class AboutMe(models.Model):

    text = models.TextField()

    def __str__(self):
        return self.text

home/views.py
from django.contrib import messages
from django.core.mail import EmailMessage
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render

from django.conf import settings
# Create your views here.
from django.views.decorators.cache import cache_page

from home.tasks import send_email
from post.models import Post

@cache_page(60*15)
def IndexView(request):

    posts = Post.objects.filter(status=True)

    page = request.GET.get('page', 1)

    paginator = Paginator(posts, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "index.html", {"posts":posts})

def AboutView(request):
    return render(request, "about.html")

@cache_page(60)
def ContactView(request):

    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        try:
            send_email.delay(name, message, email)
            messages.info(request, "Mail Yollandı")
        except:
            messages.error(request, "Mail Yollanamadı")
    return render(request, "contact.html")

home/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Hakkımda{% endblock %}
{% block content %}
<header class="masthead" style="background-image: url('{% static 'img/about-bg.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>About Me</h1>
              <span class="subheading">Hakkımda</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
        </div>
      </div>
    </div>

    <hr>
{% endblock %}

home/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %} - Utkucan Bıyıklı</title>
    <!-- Latest compiled and minified CSS -->

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
  {% block style %}
  {% endblock %}

  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home:index' %}">Utkucan Bıyıklı</a>

        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

                         <input type="text" class="searchtext form-control" placeholder="Search for...">
              <button class="search"><i class="glyphicon glyphicon-search"></i>Search</button>

          <div id="mainBody" style="display: none;"></div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="index.html">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "home:about" %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="post.html">Sample Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
            </li>

          </ul>
        </div>
      </div>
    </nav>

{% if messages %}
    <div class="container" style="margin-top: 1%">
        {% for message in messages %}
            <div class="notice notice-sm notice-{{ message.tags }}">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}
{% block content %}
{% endblock %}
<!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

    <script>
        $(".search").on("click", function (event) {
            event.preventDefault();
            var search_post = $(".searchtext").val();
            $('#mainBody').html(" ");
            $.ajax({
                   type: "POST",
                    url: "{% url 'post:allpost' %}",
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        search: search_post
                    },
                    success: function (data) {
                        var json = JSON.parse(data);
                        var result_html = "";
                        $.each(json, function (i) {
                        result_html += '<div> <a href="/post/' + json[i].slug + '">' + json[i].title + "</a></div>";
                        });
                        $("#mainBody").html(result_html);
                        $("#mainBody").show();
                    }
            });

        });
    </script>
{% block script %}
{% endblock %}
</body>
</html>

home/templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}İletişim{% endblock %}
{% block content %}
   <!-- Page Header -->
    <header class="masthead" style="background-image: url({% static 'img/contact-bg.jpg' %})">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Contact Me</h1>
              <span class="subheading">Have qddduestions? I have answers (maybe).</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
          <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
          <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
          <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
          <form name="sentMessage" id="contactForm" novalidate method="post">{% csrf_token %}
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Name</label>
                <input type="text" class="form-control" placeholder="Name" id="name" name="name" required data-validation-required-message="Please enter your name.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Email Address</label>
                <input type="email" class="form-control" placeholder="Email Address" name="email" id="email" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Message</label>
                <textarea rows="5" class="form-control" placeholder="Message" name="message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
            <div class="form-group">
              <button type="submit" class="btn btn-secondary" id="sendMessageButton">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <hr>
{% endblock %}

home/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>Utkucan Bıyıklı</h1>
              <span class="subheading">Yazılım ve diğer uğraşlar</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in posts %}
          <div class="post-preview">
            <a href="{% url 'post:detail' post.slug %}">
              <h2 class="post-title">
                {{ post.title }}
              </h2>
              <h3 class="post-subtitle">
                  {{ post.content }}
              </h3>
            </a>
            <p class="post-meta">Posted by
              <a href="#">{{ post.user }}</a>
              on {{ post.created_date }}</p>
          </div>
          <hr>
            {% endfor %}
                   <!-- Pager -->
          <div class="clearfix">

        {% if posts.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in posts.paginator.page_range %}
      {% if posts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
                    </div>




        </div>
      </div>
    </div>

    <hr>



{% endblock %}