comment/urls.py
from django.conf.urls import url

from comment import views

app_name = "comment"

urlpatterns = [
    url(r'^$', views.PostComments, name="post_comment"),
    url(r'^send/(?P<slug>[\w-]+)$', views.SendComment, name="send_comment"),


]

home/urls.py
from django.conf.urls import  *
from django.contrib import admin

import post
from home import views

urlpatterns = [
    url(r'^$', views.IndexView, name="index"),
    url(r'^about$', views.AboutView, name="about"),
    url(r'^contact', views.ContactView, name="contact"),

]

post/urls.py
from django.conf.urls import url

from post import views

app_name = "post"

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)$', views.PostDetailView, name="detail"),
    url(r'^like/(?P<slug>[\w-]+)$', views.LikePostView, name="like"),
    url(r'^dislike/(?P<slug>[\w-]+)$', views.DislikeView, name="dislike"),
    url(r'^post/$', views.allpost, name="allpost"),
    url(r'^$', views.deneme, name="lcount"),

]

post/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify


class Post(models.Model):

    user = models.ForeignKey("auth.User", related_name="posts")
    title = models.CharField(max_length=140)
    content = models.TextField()
    body = models.CharField(max_length=140)
    image = models.ImageField()
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey("Category", related_name="posts")
    like = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, max_length=60, editable=False)

    def __str__(self):
        return self.title


    def change_status(self):
        if self.status:
            self.status = False
            self.save()
        else:
            self.status = True
            self.save()

    def like_post(self):
        self.like += 1
        self.save()

    def disslike_post(self):
        self.like -= 1
        self.save()

class Category(models.Model):

    category_name = models.CharField(max_length=40)
    popularity = models.PositiveIntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category_name


@receiver(post_save, sender=Post)
def update_slug(sender, **kwargs):
    if kwargs["instance"].title != kwargs["instance"].slug:
        slug = slugify(kwargs['instance'].title.replace('ı', 'i'))
        Post.objects.filter(title=kwargs['instance'].title).update(slug=slug)


@receiver(post_save, sender=Post)
def update_popularity(sender, **kwargs):
    if kwargs["created"]:
        try:
            cat = Category.objects.get(category_name=kwargs["instance"].category.category_name)
            cat.popularity += 1
            cat.save()
        except:
            raise ValueError("Cat Does Not Exist")

post/views.py
# -*- coding: utf-8 -*-

import json

from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from comment.forms import CommentForm
from post.models import Post





def PostDetailView(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm()
    return render(request, "post_detail.html", {"post":post,"form":form})


def LikePostView(request, slug):
    response = {}
    if (request.session.has_key(slug+"like")):
        response["err"] = True
        response["text"] = "Daha Önce Oy kullanılmış"
        data = json.dumps(response)
        return HttpResponse(data)
    post = get_object_or_404(Post, slug=slug)
    request.session[slug+"like"] = True
    post.like_post()
    response["error"] = False
    response["text"] = "Oyunuz Kaydedildi"
    data = json.dumps(response)
    return HttpResponse(data)


def DislikeView(request, slug):
    response = {}
    if (request.session.has_key(slug+"like")):
        response["err"] = True
        response["text"] = "Daha Önce Oy kullanılmış"
        data = json.dumps(response)
        return HttpResponse(data)
    post = get_object_or_404(Post, slug=slug)
    request.session[slug+"dislike"] = True
    post.disslike_post()
    response["error"] = False
    response["text"] = "Oyunuz Kaydedildi"
    data = json.dumps(response)
    return HttpResponse(data)



def allpost(request):
    if request.method == 'POST':
        results = []
        change = request.POST.get("search")
        posts = Post.objects.filter(title__icontains=change)[:3]
        for post in posts:
            post_json = {}

            post_json['title'] = post.title
            post_json["content"] = post.content
            post_json["slug"] = post.slug

            results.append(post_json)
    data = json.dumps(results)
    return HttpResponse(data)

def deneme(request):
    if request.method == "POST":
        post_json = {}
        slug = request.POST.get("post")
        post = get_object_or_404(Post, slug=slug)
        like_count = post.like
        post_json["like"] = like_count
        data = json.dumps(post_json)
        return HttpResponse(data)

post/templates/post_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{{ post.title }}{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/loader.css' %}">
{% endblock %}
{% block content %}


       <!-- Page Header -->
    {% if post.image %}
        <header class="masthead" style="background-image: url('{{ MEDIA_ROOT }}{{ post.image.url }}')">
    {% else %}
    <header class="masthead" style="background-image: url({% static 'img/post-bg.jpg'%})">
        {% endif %}
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ post.title }}</h1>
              <h2 class="subheading">{{ post.body }}</h2>
              <span class="meta">Posted by
                <a href="#">{{ post.user }}</a>
                on {{ post.created_date }}<br>
                  <p><span id="post-like"></span> kere beğenilmiş.<a id="like"><i class="fa fa-thumbs-up">
                  </i></a>
                     <a id="disslike" > <i class="fa fa-thumbs-down"></i></a>
              </span></p>
            </div>
          </div>
        </div>
      </div>
    </header>
<!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
           {{ post.content }}
            </div>
        </div>
      </div>
    </article>
    <hr>
    <div class="container col-md-10">
    <div id="commentBody">
        <div class="loader"></div>

    </div>

    </div>
    <div class="container col-md-10">
    <form action="{% url 'comment:send_comment' post.slug %}" method="post">{% csrf_token %}
            {{ form.as_p }}
    <button type="submit" id="comment-btn" class="btn">Gönder</button>
    </form>
    </div>

{% endblock %}
 {% block script %}
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>

               $(document).ready(function () {
             $.ajax({
                    type: "POST",
                    url: '{% url 'post:lcount' %}',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        post: '{{ post.slug }}'
                    },
                    success: function (data) {
                        var json = JSON.parse(data);

                        $("#post-like").text(json.like);
                        $("#post-like").show();
                    }
            });

        });

        $(document).ready(function () {
            $("#like").on("click" ,function () {

           $.ajax({
               type: "POST",
               url: "{% url 'post:like' post.slug %}",
               data: {
                   csrfmiddlewaretoken: '{{ csrf_token }}',

               },
               success: function (data) {
                var json = JSON.parse(data);
                alert(json.text);
                $.ajax({
                    type: "POST",
                    url: '{% url 'post:lcount' %}',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        post: '{{ post.slug }}'
                    },
                    success: function (data) {
                        var json = JSON.parse(data);

                        $("#post-like").text(json.like);
                        $("#post-like").show();
                    }
            });
                }

        });
        });
        });

        $(document).ready(function () {
            $("#disslike").on("click" ,function () {

           $.ajax({
               type: "POST",
               url: "{% url 'post:dislike' post.slug %}",
               data: {
                   csrfmiddlewaretoken: '{{ csrf_token }}',

               },
               success: function (data) {
                var json = JSON.parse(data);
                alert(json.text);
                $.ajax({
                    type: "POST",
                    url: '{% url 'post:lcount' %}',
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        post: '{{ post.slug }}'
                    },
                    success: function (data) {
                        var json = JSON.parse(data);

                        $("#post-like").text(json.like);
                        $("#post-like").show();
                    }
            });
                }

        });
        });
        });

        $(document).ready(function () {
            setInterval(function () {
            $.ajax({
                   type: "POST",
                    url: "{% url 'comment:post_comment' %}",
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        post: '{{ post.slug }}'
                    },
                    success: function (data) {
                        var json = JSON.parse(data);
                        var result_html = "";
                        $.each(json, function (i) {

                            result_html += "<div><h1>"+ json[i].comment + "</h1></div>"
                        });
                        $("#commentBody").html(result_html);
                        $("#commentBody").show();
                        $(".loader").display = false;
                    }
            });
            },5000);


        });




    </script>
{% endblock %}