home/urls.py
from django.conf.urls import  *
from django.contrib import admin

import post
from home import views

urlpatterns = [
    url(r'^$', views.IndexView, name="index"),
    url(r'^about$', views.AboutView, name="about"),
    url(r'^contact', views.ContactView, name="contact"),

]

post/urls.py
from django.conf.urls import url

from post import views

app_name = "post"

urlpatterns = [
    url(r'^(?P<slug>[\w-]+)$', views.PostDetailView, name="detail"),
    url(r'^like/(?P<slug>[\w-]+)$', views.LikePostView, name="like"),
    url(r'^dislike/(?P<slug>[\w-]+)$', views.DislikeView, name="dislike"),
    url(r'^post/$', views.allpost, name="allpost"),
    url(r'^$', views.deneme, name="lcount"),

]

post/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify


class Post(models.Model):

    user = models.ForeignKey("auth.User", related_name="posts")
    title = models.CharField(max_length=140)
    content = models.TextField()
    body = models.CharField(max_length=140)
    image = models.ImageField()
    status = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey("Category", related_name="posts")
    like = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, max_length=60, editable=False)

    def __str__(self):
        return self.title


    def change_status(self):
        if self.status:
            self.status = False
            self.save()
        else:
            self.status = True
            self.save()

    def like_post(self):
        self.like += 1
        self.save()

    def disslike_post(self):
        self.like -= 1
        self.save()

class Category(models.Model):

    category_name = models.CharField(max_length=40)
    popularity = models.PositiveIntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.category_name


@receiver(post_save, sender=Post)
def update_slug(sender, **kwargs):
    if kwargs["instance"].title != kwargs["instance"].slug:
        slug = slugify(kwargs['instance'].title.replace('ı', 'i'))
        Post.objects.filter(title=kwargs['instance'].title).update(slug=slug)


@receiver(post_save, sender=Post)
def update_popularity(sender, **kwargs):
    if kwargs["created"]:
        try:
            cat = Category.objects.get(category_name=kwargs["instance"].category.category_name)
            cat.popularity += 1
            cat.save()
        except:
            raise ValueError("Cat Does Not Exist")

post/views.py
# -*- coding: utf-8 -*-

import json

from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from comment.forms import CommentForm
from post.models import Post





def PostDetailView(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm()
    return render(request, "post_detail.html", {"post":post,"form":form})


def LikePostView(request, slug):
    response = {}
    if (request.session.has_key(slug+"like")):
        response["err"] = True
        response["text"] = "Daha Önce Oy kullanılmış"
        data = json.dumps(response)
        return HttpResponse(data)
    post = get_object_or_404(Post, slug=slug)
    request.session[slug+"like"] = True
    post.like_post()
    response["error"] = False
    response["text"] = "Oyunuz Kaydedildi"
    data = json.dumps(response)
    return HttpResponse(data)


def DislikeView(request, slug):
    response = {}
    if (request.session.has_key(slug+"like")):
        response["err"] = True
        response["text"] = "Daha Önce Oy kullanılmış"
        data = json.dumps(response)
        return HttpResponse(data)
    post = get_object_or_404(Post, slug=slug)
    request.session[slug+"dislike"] = True
    post.disslike_post()
    response["error"] = False
    response["text"] = "Oyunuz Kaydedildi"
    data = json.dumps(response)
    return HttpResponse(data)



def allpost(request):
    if request.method == 'POST':
        results = []
        change = request.POST.get("search")
        posts = Post.objects.filter(title__icontains=change)[:3]
        for post in posts:
            post_json = {}

            post_json['title'] = post.title
            post_json["content"] = post.content
            post_json["slug"] = post.slug

            results.append(post_json)
    data = json.dumps(results)
    return HttpResponse(data)

def deneme(request):
    if request.method == "POST":
        post_json = {}
        slug = request.POST.get("post")
        post = get_object_or_404(Post, slug=slug)
        like_count = post.like
        post_json["like"] = like_count
        data = json.dumps(post_json)
        return HttpResponse(data)

AdvancedBlog/post/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Start Bootstrap Theme</title>
    <!-- Latest compiled and minified CSS -->

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'post:index' %}">Utkucan Bıyıklı</a>

        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

                         <input type="text" class="searchtext form-control" placeholder="Search for...">
              <button class="search"><i class="glyphicon glyphicon-search"></i>Search</button>

          <div id="mainBody" style="display: none;"></div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="index.html">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="about.html">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="post.html">Sample Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.html">Contact</a>
            </li>

          </ul>
        </div>
      </div>
    </nav>

{% if messages %}
    <div class="container" style="margin-top: 1%">
        {% for message in messages %}
            <div class="notice notice-sm notice-{{ message.tags }}">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}
{% block content %}
{% endblock %}
<!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

    <script>
        $(".search").on("click", function (event) {
            event.preventDefault();
            var search_post = $(".searchtext").val();
            $('#mainBody').html(" ");
            $.ajax({
                   type: "POST",
                    url: "{% url 'post:allpost' %}",
                    data: {
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        search: search_post
                    },
                    success: function (data) {
                        var json = JSON.parse(data);
                        var result_html = "";
                        $.each(json, function (i) {

                            result_html += '<div style="color:red;margin-left:25%;">' + json[i].title + '</div>';

                        });
                        $("#mainBody").html(result_html);
                        $("#mainBody").show();
                    }
            });

        });
    </script>
</body>
</html>